"""建立 27 篇用的 Houdini 測試場景。用法：ocrun houdini 22.0.429 hython make_houdini_submit_scene.py"""
import hou
OUT = "C:/opencue/render/hou/"
geo = hou.node("/obj").createNode("geo", "geo1")
box = geo.createNode("box")

conv = geo.createNode("filecache::2.0", "convert_cache")
conv.setInput(0, box)
print("filecache parms:", [p.name() for p in conv.parms() if p.name() in ("filemethod", "file", "basedir", "basename", "cachesim")])
conv.parm("filemethod").set(1)
conv.parm("file").set(OUT + "convert.$F4.bgeo.sc")
conv.parm("cachesim").set(0)
conv.parmTuple("f").deleteAllKeyframes(); conv.parmTuple("f").set((1, 4, 1))

solver = geo.createNode("solver", "sim")
solver.setInput(0, box)
s = solver.node("d/s")
xf = s.createNode("xform", "move_up")
xf.setInput(0, s.node("Prev_Frame"))
xf.parm("ty").set(0.5)
s.node("OUT").setInput(0, xf)
simcache = geo.createNode("filecache::2.0", "sim_cache")
simcache.setInput(0, solver)
simcache.parm("filemethod").set(1)
simcache.parm("file").set(OUT + "sim.$F4.bgeo.sc")
simcache.parm("cachesim").set(1)
simcache.parmTuple("f").deleteAllKeyframes(); simcache.parmTuple("f").set((1, 10, 1))

rop = geo.createNode("rop_geometry", "rop_out")
rop.setInput(0, box)
rop.parm("sopoutput").set(OUT + "rop.$F4.bgeo.sc")
rop.parm("trange").set(1)
rop.parmTuple("f").deleteAllKeyframes(); rop.parmTuple("f").set((1, 3, 1))

st = hou.node("/stage")
sph = st.createNode("sphere")
cam = st.createNode("camera"); cam.setInput(0, sph); cam.parm("tz").set(5)
k = st.createNode("karma", "karma_render"); k.setInput(0, cam)
k.parm("camera").set("/cameras/camera1")
k.parm("resolutionx").set(160); k.parm("resolutiony").set(90)
k.parm("samplesperpixel").set(1); k.parm("pathtracedsamples").set(4)
k.parm("picture").set(OUT + "karma.$F4.exr")
k.parm("trange").set(1)
k.parmTuple("f").deleteAllKeyframes(); k.parmTuple("f").set((1, 3, 1))
k.setSelected(True, clear_all_selected=True)
hou.hipFile.save("C:/opencue/scenes/hou_submit_test.hip")
print("saved", hou.hipFile.path())
